// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BusinessSelectorProtos.proto

package org.xiaoxiancai.imhere.common.protos;

public final class BusinessSelectorProtos {
  private BusinessSelectorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BusinessSelectorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.xiaoxiancai.imhere.common.protos.BusinessSelector)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool isSuccess = 1;</code>
     */
    boolean hasIsSuccess();
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    boolean getIsSuccess();

    /**
     * <code>required .org.xiaoxiancai.imhere.common.protos.BusinessType businessType = 2;</code>
     */
    boolean hasBusinessType();
    /**
     * <code>required .org.xiaoxiancai.imhere.common.protos.BusinessType businessType = 2;</code>
     */
    org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType getBusinessType();
  }
  /**
   * Protobuf type {@code org.xiaoxiancai.imhere.common.protos.BusinessSelector}
   *
   * <pre>
   * 业务选择器
   * </pre>
   */
  public static final class BusinessSelector extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.xiaoxiancai.imhere.common.protos.BusinessSelector)
      BusinessSelectorOrBuilder {
    // Use BusinessSelector.newBuilder() to construct.
    private BusinessSelector(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BusinessSelector(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BusinessSelector defaultInstance;
    public static BusinessSelector getDefaultInstance() {
      return defaultInstance;
    }

    public BusinessSelector getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BusinessSelector(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isSuccess_ = input.readBool();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType value = org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                businessType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.internal_static_org_xiaoxiancai_imhere_common_protos_BusinessSelector_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.internal_static_org_xiaoxiancai_imhere_common_protos_BusinessSelector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector.class, org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector.Builder.class);
    }

    public static com.google.protobuf.Parser<BusinessSelector> PARSER =
        new com.google.protobuf.AbstractParser<BusinessSelector>() {
      public BusinessSelector parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BusinessSelector(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BusinessSelector> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ISSUCCESS_FIELD_NUMBER = 1;
    private boolean isSuccess_;
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    public static final int BUSINESSTYPE_FIELD_NUMBER = 2;
    private org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType businessType_;
    /**
     * <code>required .org.xiaoxiancai.imhere.common.protos.BusinessType businessType = 2;</code>
     */
    public boolean hasBusinessType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .org.xiaoxiancai.imhere.common.protos.BusinessType businessType = 2;</code>
     */
    public org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType getBusinessType() {
      return businessType_;
    }

    private void initFields() {
      isSuccess_ = false;
      businessType_ = org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType.REGISTER;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIsSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBusinessType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, businessType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, businessType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.xiaoxiancai.imhere.common.protos.BusinessSelector}
     *
     * <pre>
     * 业务选择器
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.xiaoxiancai.imhere.common.protos.BusinessSelector)
        org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelectorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.internal_static_org_xiaoxiancai_imhere_common_protos_BusinessSelector_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.internal_static_org_xiaoxiancai_imhere_common_protos_BusinessSelector_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector.class, org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector.Builder.class);
      }

      // Construct using org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        businessType_ = org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType.REGISTER;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.internal_static_org_xiaoxiancai_imhere_common_protos_BusinessSelector_descriptor;
      }

      public org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector getDefaultInstanceForType() {
        return org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector.getDefaultInstance();
      }

      public org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector build() {
        org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector buildPartial() {
        org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector result = new org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isSuccess_ = isSuccess_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.businessType_ = businessType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector) {
          return mergeFrom((org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector other) {
        if (other == org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector.getDefaultInstance()) return this;
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        if (other.hasBusinessType()) {
          setBusinessType(other.getBusinessType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsSuccess()) {
          
          return false;
        }
        if (!hasBusinessType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.xiaoxiancai.imhere.common.protos.BusinessSelectorProtos.BusinessSelector) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isSuccess_ ;
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      private org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType businessType_ = org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType.REGISTER;
      /**
       * <code>required .org.xiaoxiancai.imhere.common.protos.BusinessType businessType = 2;</code>
       */
      public boolean hasBusinessType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .org.xiaoxiancai.imhere.common.protos.BusinessType businessType = 2;</code>
       */
      public org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType getBusinessType() {
        return businessType_;
      }
      /**
       * <code>required .org.xiaoxiancai.imhere.common.protos.BusinessType businessType = 2;</code>
       */
      public Builder setBusinessType(org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        businessType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .org.xiaoxiancai.imhere.common.protos.BusinessType businessType = 2;</code>
       */
      public Builder clearBusinessType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        businessType_ = org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.BusinessType.REGISTER;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.xiaoxiancai.imhere.common.protos.BusinessSelector)
    }

    static {
      defaultInstance = new BusinessSelector(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.xiaoxiancai.imhere.common.protos.BusinessSelector)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_xiaoxiancai_imhere_common_protos_BusinessSelector_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_xiaoxiancai_imhere_common_protos_BusinessSelector_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034BusinessSelectorProtos.proto\022$org.xiao" +
      "xiancai.imhere.common.protos\032\030BusinessTy" +
      "peProtos.proto\"o\n\020BusinessSelector\022\021\n\tis" +
      "Success\030\001 \002(\010\022H\n\014businessType\030\002 \002(\01622.or" +
      "g.xiaoxiancai.imhere.common.protos.Busin" +
      "essTypeB>\n$org.xiaoxiancai.imhere.common" +
      ".protosB\026BusinessSelectorProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.getDescriptor(),
        }, assigner);
    internal_static_org_xiaoxiancai_imhere_common_protos_BusinessSelector_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_xiaoxiancai_imhere_common_protos_BusinessSelector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_xiaoxiancai_imhere_common_protos_BusinessSelector_descriptor,
        new java.lang.String[] { "IsSuccess", "BusinessType", });
    org.xiaoxiancai.imhere.common.protos.BusinessTypeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
