// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AcceptFriendRequestProtos.proto

package org.xiaoxiancai.imhere.common.protos.business;

public final class AcceptFriendRequestProtos {
  private AcceptFriendRequestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AcceptFriendRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.xiaoxiancai.imhere.server.business.protos.AcceptFriendRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 fromUserId = 1;</code>
     *
     * <pre>
     * 发起用户id
     * </pre>
     */
    boolean hasFromUserId();
    /**
     * <code>required int32 fromUserId = 1;</code>
     *
     * <pre>
     * 发起用户id
     * </pre>
     */
    int getFromUserId();

    /**
     * <code>required int32 toUserId = 2;</code>
     *
     * <pre>
     * 被发起用户id
     * </pre>
     */
    boolean hasToUserId();
    /**
     * <code>required int32 toUserId = 2;</code>
     *
     * <pre>
     * 被发起用户id
     * </pre>
     */
    int getToUserId();

    /**
     * <code>required bool accept = 3;</code>
     *
     * <pre>
     * 接受与否
     * </pre>
     */
    boolean hasAccept();
    /**
     * <code>required bool accept = 3;</code>
     *
     * <pre>
     * 接受与否
     * </pre>
     */
    boolean getAccept();
  }
  /**
   * Protobuf type {@code org.xiaoxiancai.imhere.server.business.protos.AcceptFriendRequest}
   */
  public static final class AcceptFriendRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.xiaoxiancai.imhere.server.business.protos.AcceptFriendRequest)
      AcceptFriendRequestOrBuilder {
    // Use AcceptFriendRequest.newBuilder() to construct.
    private AcceptFriendRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AcceptFriendRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AcceptFriendRequest defaultInstance;
    public static AcceptFriendRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AcceptFriendRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AcceptFriendRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              fromUserId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              toUserId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              accept_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_AcceptFriendRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_AcceptFriendRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest.class, org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AcceptFriendRequest> PARSER =
        new com.google.protobuf.AbstractParser<AcceptFriendRequest>() {
      public AcceptFriendRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AcceptFriendRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AcceptFriendRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FROMUSERID_FIELD_NUMBER = 1;
    private int fromUserId_;
    /**
     * <code>required int32 fromUserId = 1;</code>
     *
     * <pre>
     * 发起用户id
     * </pre>
     */
    public boolean hasFromUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 fromUserId = 1;</code>
     *
     * <pre>
     * 发起用户id
     * </pre>
     */
    public int getFromUserId() {
      return fromUserId_;
    }

    public static final int TOUSERID_FIELD_NUMBER = 2;
    private int toUserId_;
    /**
     * <code>required int32 toUserId = 2;</code>
     *
     * <pre>
     * 被发起用户id
     * </pre>
     */
    public boolean hasToUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 toUserId = 2;</code>
     *
     * <pre>
     * 被发起用户id
     * </pre>
     */
    public int getToUserId() {
      return toUserId_;
    }

    public static final int ACCEPT_FIELD_NUMBER = 3;
    private boolean accept_;
    /**
     * <code>required bool accept = 3;</code>
     *
     * <pre>
     * 接受与否
     * </pre>
     */
    public boolean hasAccept() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool accept = 3;</code>
     *
     * <pre>
     * 接受与否
     * </pre>
     */
    public boolean getAccept() {
      return accept_;
    }

    private void initFields() {
      fromUserId_ = 0;
      toUserId_ = 0;
      accept_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFromUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccept()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, accept_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, accept_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.xiaoxiancai.imhere.server.business.protos.AcceptFriendRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.xiaoxiancai.imhere.server.business.protos.AcceptFriendRequest)
        org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_AcceptFriendRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_AcceptFriendRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest.class, org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest.Builder.class);
      }

      // Construct using org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        toUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        accept_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_AcceptFriendRequest_descriptor;
      }

      public org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest getDefaultInstanceForType() {
        return org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest.getDefaultInstance();
      }

      public org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest build() {
        org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest buildPartial() {
        org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest result = new org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromUserId_ = fromUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toUserId_ = toUserId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.accept_ = accept_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest) {
          return mergeFrom((org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest other) {
        if (other == org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest.getDefaultInstance()) return this;
        if (other.hasFromUserId()) {
          setFromUserId(other.getFromUserId());
        }
        if (other.hasToUserId()) {
          setToUserId(other.getToUserId());
        }
        if (other.hasAccept()) {
          setAccept(other.getAccept());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFromUserId()) {
          
          return false;
        }
        if (!hasToUserId()) {
          
          return false;
        }
        if (!hasAccept()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.xiaoxiancai.imhere.common.protos.business.AcceptFriendRequestProtos.AcceptFriendRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int fromUserId_ ;
      /**
       * <code>required int32 fromUserId = 1;</code>
       *
       * <pre>
       * 发起用户id
       * </pre>
       */
      public boolean hasFromUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 fromUserId = 1;</code>
       *
       * <pre>
       * 发起用户id
       * </pre>
       */
      public int getFromUserId() {
        return fromUserId_;
      }
      /**
       * <code>required int32 fromUserId = 1;</code>
       *
       * <pre>
       * 发起用户id
       * </pre>
       */
      public Builder setFromUserId(int value) {
        bitField0_ |= 0x00000001;
        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 fromUserId = 1;</code>
       *
       * <pre>
       * 发起用户id
       * </pre>
       */
      public Builder clearFromUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromUserId_ = 0;
        onChanged();
        return this;
      }

      private int toUserId_ ;
      /**
       * <code>required int32 toUserId = 2;</code>
       *
       * <pre>
       * 被发起用户id
       * </pre>
       */
      public boolean hasToUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 toUserId = 2;</code>
       *
       * <pre>
       * 被发起用户id
       * </pre>
       */
      public int getToUserId() {
        return toUserId_;
      }
      /**
       * <code>required int32 toUserId = 2;</code>
       *
       * <pre>
       * 被发起用户id
       * </pre>
       */
      public Builder setToUserId(int value) {
        bitField0_ |= 0x00000002;
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 toUserId = 2;</code>
       *
       * <pre>
       * 被发起用户id
       * </pre>
       */
      public Builder clearToUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toUserId_ = 0;
        onChanged();
        return this;
      }

      private boolean accept_ ;
      /**
       * <code>required bool accept = 3;</code>
       *
       * <pre>
       * 接受与否
       * </pre>
       */
      public boolean hasAccept() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool accept = 3;</code>
       *
       * <pre>
       * 接受与否
       * </pre>
       */
      public boolean getAccept() {
        return accept_;
      }
      /**
       * <code>required bool accept = 3;</code>
       *
       * <pre>
       * 接受与否
       * </pre>
       */
      public Builder setAccept(boolean value) {
        bitField0_ |= 0x00000004;
        accept_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool accept = 3;</code>
       *
       * <pre>
       * 接受与否
       * </pre>
       */
      public Builder clearAccept() {
        bitField0_ = (bitField0_ & ~0x00000004);
        accept_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.xiaoxiancai.imhere.server.business.protos.AcceptFriendRequest)
    }

    static {
      defaultInstance = new AcceptFriendRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.xiaoxiancai.imhere.server.business.protos.AcceptFriendRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_xiaoxiancai_imhere_server_business_protos_AcceptFriendRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_xiaoxiancai_imhere_server_business_protos_AcceptFriendRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037AcceptFriendRequestProtos.proto\022-org.x" +
      "iaoxiancai.imhere.server.business.protos" +
      "\"K\n\023AcceptFriendRequest\022\022\n\nfromUserId\030\001 " +
      "\002(\005\022\020\n\010toUserId\030\002 \002(\005\022\016\n\006accept\030\003 \002(\010BJ\n" +
      "-org.xiaoxiancai.imhere.common.protos.bu" +
      "sinessB\031AcceptFriendRequestProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_xiaoxiancai_imhere_server_business_protos_AcceptFriendRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_xiaoxiancai_imhere_server_business_protos_AcceptFriendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_xiaoxiancai_imhere_server_business_protos_AcceptFriendRequest_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", "Accept", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
