// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddFriendRequest.proto

package org.xiaoxiancai.imhere.common.protos.business;

public final class AddFriendResponseProtos {
  private AddFriendResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AddFriendResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.xiaoxiancai.imhere.server.business.protos.AddFriendResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool accept = 1;</code>
     *
     * <pre>
     * 是否接受
     * </pre>
     */
    boolean hasAccept();
    /**
     * <code>required bool accept = 1;</code>
     *
     * <pre>
     * 是否接受
     * </pre>
     */
    boolean getAccept();
  }
  /**
   * Protobuf type {@code org.xiaoxiancai.imhere.server.business.protos.AddFriendResponse}
   */
  public static final class AddFriendResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.xiaoxiancai.imhere.server.business.protos.AddFriendResponse)
      AddFriendResponseOrBuilder {
    // Use AddFriendResponse.newBuilder() to construct.
    private AddFriendResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddFriendResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddFriendResponse defaultInstance;
    public static AddFriendResponse getDefaultInstance() {
      return defaultInstance;
    }

    public AddFriendResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddFriendResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              accept_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_AddFriendResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_AddFriendResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse.class, org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<AddFriendResponse> PARSER =
        new com.google.protobuf.AbstractParser<AddFriendResponse>() {
      public AddFriendResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddFriendResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddFriendResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ACCEPT_FIELD_NUMBER = 1;
    private boolean accept_;
    /**
     * <code>required bool accept = 1;</code>
     *
     * <pre>
     * 是否接受
     * </pre>
     */
    public boolean hasAccept() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool accept = 1;</code>
     *
     * <pre>
     * 是否接受
     * </pre>
     */
    public boolean getAccept() {
      return accept_;
    }

    private void initFields() {
      accept_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAccept()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, accept_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, accept_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.xiaoxiancai.imhere.server.business.protos.AddFriendResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.xiaoxiancai.imhere.server.business.protos.AddFriendResponse)
        org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_AddFriendResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_AddFriendResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse.class, org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse.Builder.class);
      }

      // Construct using org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accept_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_AddFriendResponse_descriptor;
      }

      public org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse getDefaultInstanceForType() {
        return org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse.getDefaultInstance();
      }

      public org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse build() {
        org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse buildPartial() {
        org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse result = new org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accept_ = accept_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse) {
          return mergeFrom((org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse other) {
        if (other == org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse.getDefaultInstance()) return this;
        if (other.hasAccept()) {
          setAccept(other.getAccept());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccept()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.xiaoxiancai.imhere.common.protos.business.AddFriendResponseProtos.AddFriendResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean accept_ ;
      /**
       * <code>required bool accept = 1;</code>
       *
       * <pre>
       * 是否接受
       * </pre>
       */
      public boolean hasAccept() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool accept = 1;</code>
       *
       * <pre>
       * 是否接受
       * </pre>
       */
      public boolean getAccept() {
        return accept_;
      }
      /**
       * <code>required bool accept = 1;</code>
       *
       * <pre>
       * 是否接受
       * </pre>
       */
      public Builder setAccept(boolean value) {
        bitField0_ |= 0x00000001;
        accept_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool accept = 1;</code>
       *
       * <pre>
       * 是否接受
       * </pre>
       */
      public Builder clearAccept() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accept_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.xiaoxiancai.imhere.server.business.protos.AddFriendResponse)
    }

    static {
      defaultInstance = new AddFriendResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.xiaoxiancai.imhere.server.business.protos.AddFriendResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_xiaoxiancai_imhere_server_business_protos_AddFriendResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_xiaoxiancai_imhere_server_business_protos_AddFriendResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026AddFriendRequest.proto\022-org.xiaoxianca" +
      "i.imhere.server.business.protos\"#\n\021AddFr" +
      "iendResponse\022\016\n\006accept\030\001 \002(\010BH\n-org.xiao" +
      "xiancai.imhere.common.protos.businessB\027A" +
      "ddFriendResponseProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_xiaoxiancai_imhere_server_business_protos_AddFriendResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_xiaoxiancai_imhere_server_business_protos_AddFriendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_xiaoxiancai_imhere_server_business_protos_AddFriendResponse_descriptor,
        new java.lang.String[] { "Accept", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
