// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocateResponseProtos.proto

package org.xiaoxiancai.imhere.common.protos.business;

public final class LocateResponseProtos {
  private LocateResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LocateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.xiaoxiancai.imhere.server.business.protos.LocateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool isSuccess = 1;</code>
     *
     * <pre>
     * 定位成功否
     * </pre>
     */
    boolean hasIsSuccess();
    /**
     * <code>required bool isSuccess = 1;</code>
     *
     * <pre>
     * 定位成功否
     * </pre>
     */
    boolean getIsSuccess();

    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     * 状态码
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     * 状态码
     * </pre>
     */
    int getStatus();

    /**
     * <code>optional string message = 3;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 3;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 3;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
     *
     * <pre>
     * 朋友位置信息
     * </pre>
     */
    java.util.List<org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location> 
        getFriendLocationsList();
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
     *
     * <pre>
     * 朋友位置信息
     * </pre>
     */
    org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location getFriendLocations(int index);
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
     *
     * <pre>
     * 朋友位置信息
     * </pre>
     */
    int getFriendLocationsCount();
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
     *
     * <pre>
     * 朋友位置信息
     * </pre>
     */
    java.util.List<? extends org.xiaoxiancai.imhere.common.protos.business.LocationProtos.LocationOrBuilder> 
        getFriendLocationsOrBuilderList();
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
     *
     * <pre>
     * 朋友位置信息
     * </pre>
     */
    org.xiaoxiancai.imhere.common.protos.business.LocationProtos.LocationOrBuilder getFriendLocationsOrBuilder(
        int index);

    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
     */
    java.util.List<org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command> getCommandsList();
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
     */
    int getCommandsCount();
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
     */
    org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command getCommands(int index);
  }
  /**
   * Protobuf type {@code org.xiaoxiancai.imhere.server.business.protos.LocateResponse}
   */
  public static final class LocateResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.xiaoxiancai.imhere.server.business.protos.LocateResponse)
      LocateResponseOrBuilder {
    // Use LocateResponse.newBuilder() to construct.
    private LocateResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LocateResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LocateResponse defaultInstance;
    public static LocateResponse getDefaultInstance() {
      return defaultInstance;
    }

    public LocateResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LocateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isSuccess_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              message_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                friendLocations_ = new java.util.ArrayList<org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location>();
                mutable_bitField0_ |= 0x00000008;
              }
              friendLocations_.add(input.readMessage(org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.PARSER, extensionRegistry));
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command value = org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
                } else {
                if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                  commands_ = new java.util.ArrayList<org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command>();
                  mutable_bitField0_ |= 0x00000010;
                }
                commands_.add(value);
              }
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command value = org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(5, rawValue);
                  } else {
                  if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                    commands_ = new java.util.ArrayList<org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command>();
                    mutable_bitField0_ |= 0x00000010;
                  }
                  commands_.add(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          friendLocations_ = java.util.Collections.unmodifiableList(friendLocations_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          commands_ = java.util.Collections.unmodifiableList(commands_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_LocateResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_LocateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse.class, org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<LocateResponse> PARSER =
        new com.google.protobuf.AbstractParser<LocateResponse>() {
      public LocateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocateResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LocateResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ISSUCCESS_FIELD_NUMBER = 1;
    private boolean isSuccess_;
    /**
     * <code>required bool isSuccess = 1;</code>
     *
     * <pre>
     * 定位成功否
     * </pre>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isSuccess = 1;</code>
     *
     * <pre>
     * 定位成功否
     * </pre>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     * 状态码
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     * 状态码
     * </pre>
     */
    public int getStatus() {
      return status_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 3;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string message = 3;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 3;</code>
     *
     * <pre>
     * 附加信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRIENDLOCATIONS_FIELD_NUMBER = 4;
    private java.util.List<org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location> friendLocations_;
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
     *
     * <pre>
     * 朋友位置信息
     * </pre>
     */
    public java.util.List<org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location> getFriendLocationsList() {
      return friendLocations_;
    }
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
     *
     * <pre>
     * 朋友位置信息
     * </pre>
     */
    public java.util.List<? extends org.xiaoxiancai.imhere.common.protos.business.LocationProtos.LocationOrBuilder> 
        getFriendLocationsOrBuilderList() {
      return friendLocations_;
    }
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
     *
     * <pre>
     * 朋友位置信息
     * </pre>
     */
    public int getFriendLocationsCount() {
      return friendLocations_.size();
    }
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
     *
     * <pre>
     * 朋友位置信息
     * </pre>
     */
    public org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location getFriendLocations(int index) {
      return friendLocations_.get(index);
    }
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
     *
     * <pre>
     * 朋友位置信息
     * </pre>
     */
    public org.xiaoxiancai.imhere.common.protos.business.LocationProtos.LocationOrBuilder getFriendLocationsOrBuilder(
        int index) {
      return friendLocations_.get(index);
    }

    public static final int COMMANDS_FIELD_NUMBER = 5;
    private java.util.List<org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command> commands_;
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
     */
    public java.util.List<org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command> getCommandsList() {
      return commands_;
    }
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
     */
    public int getCommandsCount() {
      return commands_.size();
    }
    /**
     * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
     */
    public org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command getCommands(int index) {
      return commands_.get(index);
    }

    private void initFields() {
      isSuccess_ = false;
      status_ = 0;
      message_ = "";
      friendLocations_ = java.util.Collections.emptyList();
      commands_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIsSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFriendLocationsCount(); i++) {
        if (!getFriendLocations(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMessageBytes());
      }
      for (int i = 0; i < friendLocations_.size(); i++) {
        output.writeMessage(4, friendLocations_.get(i));
      }
      for (int i = 0; i < commands_.size(); i++) {
        output.writeEnum(5, commands_.get(i).getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMessageBytes());
      }
      for (int i = 0; i < friendLocations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, friendLocations_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < commands_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(commands_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * commands_.size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.xiaoxiancai.imhere.server.business.protos.LocateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.xiaoxiancai.imhere.server.business.protos.LocateResponse)
        org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_LocateResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_LocateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse.class, org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse.Builder.class);
      }

      // Construct using org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFriendLocationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (friendLocationsBuilder_ == null) {
          friendLocations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          friendLocationsBuilder_.clear();
        }
        commands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.internal_static_org_xiaoxiancai_imhere_server_business_protos_LocateResponse_descriptor;
      }

      public org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse getDefaultInstanceForType() {
        return org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse.getDefaultInstance();
      }

      public org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse build() {
        org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse buildPartial() {
        org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse result = new org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isSuccess_ = isSuccess_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.message_ = message_;
        if (friendLocationsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            friendLocations_ = java.util.Collections.unmodifiableList(friendLocations_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.friendLocations_ = friendLocations_;
        } else {
          result.friendLocations_ = friendLocationsBuilder_.build();
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          commands_ = java.util.Collections.unmodifiableList(commands_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.commands_ = commands_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse) {
          return mergeFrom((org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse other) {
        if (other == org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse.getDefaultInstance()) return this;
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000004;
          message_ = other.message_;
          onChanged();
        }
        if (friendLocationsBuilder_ == null) {
          if (!other.friendLocations_.isEmpty()) {
            if (friendLocations_.isEmpty()) {
              friendLocations_ = other.friendLocations_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureFriendLocationsIsMutable();
              friendLocations_.addAll(other.friendLocations_);
            }
            onChanged();
          }
        } else {
          if (!other.friendLocations_.isEmpty()) {
            if (friendLocationsBuilder_.isEmpty()) {
              friendLocationsBuilder_.dispose();
              friendLocationsBuilder_ = null;
              friendLocations_ = other.friendLocations_;
              bitField0_ = (bitField0_ & ~0x00000008);
              friendLocationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFriendLocationsFieldBuilder() : null;
            } else {
              friendLocationsBuilder_.addAllMessages(other.friendLocations_);
            }
          }
        }
        if (!other.commands_.isEmpty()) {
          if (commands_.isEmpty()) {
            commands_ = other.commands_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCommandsIsMutable();
            commands_.addAll(other.commands_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsSuccess()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        for (int i = 0; i < getFriendLocationsCount(); i++) {
          if (!getFriendLocations(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.xiaoxiancai.imhere.common.protos.business.LocateResponseProtos.LocateResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isSuccess_ ;
      /**
       * <code>required bool isSuccess = 1;</code>
       *
       * <pre>
       * 定位成功否
       * </pre>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       *
       * <pre>
       * 定位成功否
       * </pre>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       *
       * <pre>
       * 定位成功否
       * </pre>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       *
       * <pre>
       * 定位成功否
       * </pre>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       * 状态码
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       * 状态码
       * </pre>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       * 状态码
       * </pre>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       * 状态码
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 3;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string message = 3;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       *
       * <pre>
       * 附加信息
       * </pre>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }

      private java.util.List<org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location> friendLocations_ =
        java.util.Collections.emptyList();
      private void ensureFriendLocationsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          friendLocations_ = new java.util.ArrayList<org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location>(friendLocations_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location, org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.Builder, org.xiaoxiancai.imhere.common.protos.business.LocationProtos.LocationOrBuilder> friendLocationsBuilder_;

      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public java.util.List<org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location> getFriendLocationsList() {
        if (friendLocationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(friendLocations_);
        } else {
          return friendLocationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public int getFriendLocationsCount() {
        if (friendLocationsBuilder_ == null) {
          return friendLocations_.size();
        } else {
          return friendLocationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location getFriendLocations(int index) {
        if (friendLocationsBuilder_ == null) {
          return friendLocations_.get(index);
        } else {
          return friendLocationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public Builder setFriendLocations(
          int index, org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location value) {
        if (friendLocationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendLocationsIsMutable();
          friendLocations_.set(index, value);
          onChanged();
        } else {
          friendLocationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public Builder setFriendLocations(
          int index, org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.Builder builderForValue) {
        if (friendLocationsBuilder_ == null) {
          ensureFriendLocationsIsMutable();
          friendLocations_.set(index, builderForValue.build());
          onChanged();
        } else {
          friendLocationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public Builder addFriendLocations(org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location value) {
        if (friendLocationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendLocationsIsMutable();
          friendLocations_.add(value);
          onChanged();
        } else {
          friendLocationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public Builder addFriendLocations(
          int index, org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location value) {
        if (friendLocationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendLocationsIsMutable();
          friendLocations_.add(index, value);
          onChanged();
        } else {
          friendLocationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public Builder addFriendLocations(
          org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.Builder builderForValue) {
        if (friendLocationsBuilder_ == null) {
          ensureFriendLocationsIsMutable();
          friendLocations_.add(builderForValue.build());
          onChanged();
        } else {
          friendLocationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public Builder addFriendLocations(
          int index, org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.Builder builderForValue) {
        if (friendLocationsBuilder_ == null) {
          ensureFriendLocationsIsMutable();
          friendLocations_.add(index, builderForValue.build());
          onChanged();
        } else {
          friendLocationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public Builder addAllFriendLocations(
          java.lang.Iterable<? extends org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location> values) {
        if (friendLocationsBuilder_ == null) {
          ensureFriendLocationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, friendLocations_);
          onChanged();
        } else {
          friendLocationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public Builder clearFriendLocations() {
        if (friendLocationsBuilder_ == null) {
          friendLocations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          friendLocationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public Builder removeFriendLocations(int index) {
        if (friendLocationsBuilder_ == null) {
          ensureFriendLocationsIsMutable();
          friendLocations_.remove(index);
          onChanged();
        } else {
          friendLocationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.Builder getFriendLocationsBuilder(
          int index) {
        return getFriendLocationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public org.xiaoxiancai.imhere.common.protos.business.LocationProtos.LocationOrBuilder getFriendLocationsOrBuilder(
          int index) {
        if (friendLocationsBuilder_ == null) {
          return friendLocations_.get(index);  } else {
          return friendLocationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public java.util.List<? extends org.xiaoxiancai.imhere.common.protos.business.LocationProtos.LocationOrBuilder> 
           getFriendLocationsOrBuilderList() {
        if (friendLocationsBuilder_ != null) {
          return friendLocationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(friendLocations_);
        }
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.Builder addFriendLocationsBuilder() {
        return getFriendLocationsFieldBuilder().addBuilder(
            org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.getDefaultInstance());
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.Builder addFriendLocationsBuilder(
          int index) {
        return getFriendLocationsFieldBuilder().addBuilder(
            index, org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.getDefaultInstance());
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Location friendLocations = 4;</code>
       *
       * <pre>
       * 朋友位置信息
       * </pre>
       */
      public java.util.List<org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.Builder> 
           getFriendLocationsBuilderList() {
        return getFriendLocationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location, org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.Builder, org.xiaoxiancai.imhere.common.protos.business.LocationProtos.LocationOrBuilder> 
          getFriendLocationsFieldBuilder() {
        if (friendLocationsBuilder_ == null) {
          friendLocationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location, org.xiaoxiancai.imhere.common.protos.business.LocationProtos.Location.Builder, org.xiaoxiancai.imhere.common.protos.business.LocationProtos.LocationOrBuilder>(
                  friendLocations_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          friendLocations_ = null;
        }
        return friendLocationsBuilder_;
      }

      private java.util.List<org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command> commands_ =
        java.util.Collections.emptyList();
      private void ensureCommandsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          commands_ = new java.util.ArrayList<org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command>(commands_);
          bitField0_ |= 0x00000010;
        }
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
       */
      public java.util.List<org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command> getCommandsList() {
        return java.util.Collections.unmodifiableList(commands_);
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
       */
      public int getCommandsCount() {
        return commands_.size();
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
       */
      public org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command getCommands(int index) {
        return commands_.get(index);
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
       */
      public Builder setCommands(
          int index, org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
       */
      public Builder addCommands(org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
       */
      public Builder addAllCommands(
          java.lang.Iterable<? extends org.xiaoxiancai.imhere.common.protos.business.CommandProtos.Command> values) {
        ensureCommandsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, commands_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.xiaoxiancai.imhere.server.business.protos.Command commands = 5;</code>
       */
      public Builder clearCommands() {
        commands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.xiaoxiancai.imhere.server.business.protos.LocateResponse)
    }

    static {
      defaultInstance = new LocateResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.xiaoxiancai.imhere.server.business.protos.LocateResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_xiaoxiancai_imhere_server_business_protos_LocateResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_xiaoxiancai_imhere_server_business_protos_LocateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032LocateResponseProtos.proto\022-org.xiaoxi" +
      "ancai.imhere.server.business.protos\032\024Loc" +
      "ationProtos.proto\032\023CommandProtos.proto\"\340" +
      "\001\n\016LocateResponse\022\021\n\tisSuccess\030\001 \002(\010\022\016\n\006" +
      "status\030\002 \002(\005\022\017\n\007message\030\003 \001(\t\022P\n\017friendL" +
      "ocations\030\004 \003(\01327.org.xiaoxiancai.imhere." +
      "server.business.protos.Location\022H\n\010comma" +
      "nds\030\005 \003(\01626.org.xiaoxiancai.imhere.serve" +
      "r.business.protos.CommandBE\n-org.xiaoxia" +
      "ncai.imhere.common.protos.businessB\024Loca",
      "teResponseProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.xiaoxiancai.imhere.common.protos.business.LocationProtos.getDescriptor(),
          org.xiaoxiancai.imhere.common.protos.business.CommandProtos.getDescriptor(),
        }, assigner);
    internal_static_org_xiaoxiancai_imhere_server_business_protos_LocateResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_xiaoxiancai_imhere_server_business_protos_LocateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_xiaoxiancai_imhere_server_business_protos_LocateResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Status", "Message", "FriendLocations", "Commands", });
    org.xiaoxiancai.imhere.common.protos.business.LocationProtos.getDescriptor();
    org.xiaoxiancai.imhere.common.protos.business.CommandProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
